version: "3.8"

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"   # opzionale (utile per Mongo Compass dal PC)
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/admin", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  area-personale:
    image: area-personale:1.0 
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: ricaricheDB
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: "true"
    networks:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

networks:
  backend:
    driver: overlay

volumes:
  mongo_data:
