version: "3.8"

services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    restart: unless-stopped

  area-personale:
    build:
      context: .
      dockerfile: Dockerfile
    image: area-personale:1.0
    networks:
      - backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/ricaricheDB
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: "true"
    restart: unless-stopped

networks:
  backend:

volumes:
  mongo_data:
